### ISSUE TITLE
Upgrade to released CRA 5

### ISSUE THREAD

**Issue by skypyxis** [DalSoft/create-react-app-webpack-5-module-federation-tailwind-typeScript#1]
Could you please upgrade to the new CRA 5?

**Comment by DalSoft** [comment]
Yeah I'm just testing and fixing a couple of issues

**Comment by DalSoft** [comment]
Done and fixed typescript [import resolution issue](https://github.com/import-js/eslint-plugin-import/issues/1485) too.
