### ISSUE TITLE
Documentation missing installation instructions

### ISSUE THREAD

**Issue by numbersmatter** [DalSoft/create-react-app-webpack-5-module-federation-tailwind-typeScript#2]
Thank-you for the work placed to attempt to solve this issue. I arrived at this template from https://stackoverflow.com/questions/67297300/how-to-use-webpack-module-federation-plugin-with-create-react-app-without-ejecti

I would have loved to use your template and see how far I could get.  Unfortunately, lack of installation documentation left me unable to test template or give it a star.

How do I install and use your template?

```
#From terminal 
npx create-react-app microfrontend --template

```

Again thank-you for releasing your template. I only seek to suggest that documenting this crucial first step may lead to wider adoption and appreciation of your work. 

-L

**Comment by DalSoft** [comment]
It's a github template.

![image](https://user-images.githubusercontent.com/406007/157856102-052869dd-18bb-4458-8857-4598d1284a14.png)

Then `yarn start`

Edit modulefederation.config.js in each app to config Module Federation like exposing a component.

**Comment by numbersmatter** [comment]
Oh okay! I was so confused I thought this was a cra template. My bad! I will try it from there.

-L

**Comment by DalSoft** [comment]
Np if you need any help after getting setup just raise another issue.
