### ISSUE TITLE
Tailwind classes doesn't work

### ISSUE THREAD

**Issue by codestitch** [DalSoft/create-react-app-webpack-5-module-federation-tailwind-typeScript#5]
After installing app1 and app2. Running them both. 

I noticed that not all tailwind classes in the button component(which is from app2) reflect in tailwind classes in the host app (app1).

And the only way to fix this is by importing the tailwind unto button component.

Is there way that tailwind configured globally (in host app) reads tailwind classes in remote app?

**Comment by DalSoft** [comment]
Yeah I noticed that, the button is shared but the button Tailwind styles aren't coming over. The reason for this is (quote from linked issue):

> "With any UI library (TailwindCSS) or CSS setup that uses the Purge PostCSS plugin, then this becomes a more involved issue, as the generated CSS bundle for the host application will only look at direct dependents."

This is a limitation with Module Feduration currently, with the hindsight of this limitation Tailwind probably wasn't a good pick for a shared component example. I added it mainly to prove that you can get Tailwind 2 (and now 3) working with CRA.

[This issue](https://github.com/nrwl/nx/issues/9784#issuecomment-1095128433) explains the complexities of using PostCSS plugin and Module Federation much better than I can. It also shows some work arounds you can try.

I'll try and update the example with one of the workarounds when I get some time.
